---
- name: set parameters
  sysctl: name={{ item.name }} value={{ item.value }} state=present sysctl_file={{ kernel_parameter_file_path }}
  ignore_errors: True
  with_items: "{{ kernel_parameters }}"
